apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 548005256813.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 548005256813.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e057ef6d
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
